---
apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-http-to-amqp
  namespace: replace_namespace
data:
  activemq-http-to-amqp.json: |-
    {
      "openapi": "3.0.3",
      "info": {
        "title": "activemq-http-to-amqp",
        "version": "1.0.0"
      },
      "security": [],
      "paths": {},
      "components": {
        "securitySchemes": {}
      },
      "x-tyk-streaming": {
        "streams": {
          "consumer-stream": {
            "input": {
              "amqp_1": {
                "urls": [
                  "amqp://replace_svc_name:replace_svc_port"
                ],
                "source_address": "/test"
              }
            },
            "output": {
              "http_server": {
                "stream_path": "/consume/stream"
              }
            }
          },
          "consumer-ws": {
            "input": {
              "amqp_1": {
                "urls": [
                  "amqp://replace_svc_name:replace_svc_port"
                ],
                "source_address": "/test"
              }
            },
            "output": {
              "http_server": {
                "ws_path": "/consume/ws"
              }
            }
          },
          "producer": {
            "input": {
              "http_server": {
                "path": "/produce"
              }
            },
            "output": {
              "amqp_1": {
                "urls": [
                  "amqp://replace_svc_name:replace_svc_port"
                ],
                "target_address": "/test"
              }
            }
          }
        }
      },
      "x-tyk-api-gateway": {
        "info": {
          "name": "activemq-http-to-amqp",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/activemq-http-to-amqp/"
          }
        },
        "upstream": {
          "url": "http://httpbin.org/"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykStreamsApiDefinition
metadata:
  name: activemq-http-to-amqp
  namespace: replace_namespace
spec:
  tykStreams:
    configmapRef:
      name: activemq-http-to-amqp
      namespace: replace_namespace
      keyName: activemq-http-to-amqp.json
