apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-kafka-producer
  template:
    metadata:
      labels:
        app: notifications-kafka-producer
    spec:
      containers:
        - image: zalbiraw/go-api-test-service:v3.4
          imagePullPolicy: IfNotPresent
          name: notifications-kafka-producer
          command:
            - ./services/kafka/notifications/producer
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "tyk-opentelemetry-opentelemetry-collector:4317"
            - name: KAFKA_BROKER_URL
              value: "replace_svc_name:replace_svc_port"
            - name: KAFKA_TOPIC
              value: "replace_topic"
            - name: PRODUCE_INTERVAL
              value: "5s"
